#!/usr/bin/env bash
here=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
chmod +x $here/ONE
chmod +x $here/ALL

for f in $(find $here/docs -type f  -name "[[:lower:]]*.md"); do
  g=${f%.*}.lisp
  top=$(cat $here/docs/lib/top.lisp)
 if [ "$f" -nt "$g" ]; then
    echo "f $f g $g"
    cat $f | gawk -v Top="$top" -v Slash="$here" '
      BEGIN                               { print Top;  
                                            Comment="; " }
      sub(/load "\//,"load \"" Slash "/") {               print $0; next }
      sub(/```lisp/,"")                   { Comment=""  ; print   ; next }
      sub(/```/,"")                       { Comment="; "; print   ; next }
                                          {               print Comment $0 }
      ' > $g
  fi
done

want=$here/docs/lib/top.lisp
mkdir -p $(dirname $want)
[ -f "$want" ] || cat<<'EOF'>$want
(or (fboundp 'env)  (defun env  (x &optional d) (or #+CLISP (ext:getenv x) #+SBCL (sb-unix::posix-getenv x) d))) (or (fboundp 'want) (defun uses (f)             (load (format nil "~a/~a" (env "Gator" ".") f))))
EOF


want=$here/.gitignore
[ -f "$want" ] || cat<<'EOF'>$want
*.lisp
*~
EOF

if [ -n "$1" ]; then
  g=${1%.*}.lisp
  shift
  if [ -t 1 ]
  then         Gator=$here/docs sbcl --script $g $* 2> >(gawk '1 {print} /^5:/ {exit}') 
  else cat - | Gator=$here/docs sbcl --script $g $* 2> >(gawk '1 {print} /^5:/ {exit}')
  fi
fi
